apiVersion: v2
name: jackett
description: API Support for your favorite torrent trackers
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/jackett
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
sources:
  - https://github.com/Jackett/Jackett
  - https://github.com/k8s-at-home/container-images
dependencies:
  - name: jackett
    repository: https://k8s-at-home.com/charts/
    version: 11.7.2

type: application

# Note: k8s-at-home repository is no longer maintained
version: "11.7.2"

# renovate: datasource=github-releases depName=Jackett/Jackett
appVersion: v0.24.1234

keywords:
  - jackett
  - torrent
